[package]
name = "advent-2021"
version = "0.1.0"
authors = ["Chris Lieb <chris.lieb@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
itertools = "0.10.1"
maplit = "1.0.2"
num = "0.4.0"
regex = "1.5.4"
